version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: simulador_ir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      
  frontend:
    container_name: frontend
    build:
      context: ../apps/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../apps/frontend:/app
    command: ["npm", "run", "dev"]

  backend:
    container_name: backend
    build:
      context: ../apps/backend
      dockerfile: ../../docker/Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ../apps/backend:/app
    depends_on:
      - postgres
    command: ["npm", "run", "start:dev"]