version: '3.8'
services:
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../apps/frontend:/app
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ../apps/backend
      dockerfile: ../../docker/Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ../apps/backend:/app
    command: ["npm", "run", "start:dev"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simulador_ir
    ports:
      - "5432:5432"
